<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-53031-1661258910/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {} kilometer.".format(planet,diameter))

The diameter of Earth kilometer.


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
print(np.ones(10)*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [11]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd


In [15]:
data = [10,20,30]
df=pd.DataFrame(data,columns=['numbers'])
print(df)

   numbers
0       10
1       20
2       30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [16]:
import datetime
test_date= datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
K = 41
date_gen=pd.date_range(test_date,periods=K)
print(date_gen.strftime("d-%m-%Y"))
  

Index(['d-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023',
       'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023',
       'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023',
       'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023',
       'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023',
       'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023', 'd-01-2023',
       'd-01-2023', 'd-02-2023', 'd-02-2023', 'd-02-2023', 'd-02-2023',
       'd-02-2023', 'd-02-2023', 'd-02-2023', 'd-02-2023', 'd-02-2023',
       'd-02-2023'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [17]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [18]:
df = pd.DataFrame(lists, columns =['sno','name', 'value'])
print(df )

   sno name  value
0    1  aaa     22
1    2  bbb     25
2    3  ccc     24
