# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The daimeter of {} is {} kilometers.".format(planet,diameter))

The daimeter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
print(np.ones(10)*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd


In [14]:
data=[4,5,6]
of=pd.DataFrame(data,columns=['DATAFRAME'])

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
import datetime
t_date=datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
k=41
date_gen=pd.date_range(t_date,periods=k)
print(date_gen.strftime("%d_%m_%Y"))

Index(['01_01_2023', '02_01_2023', '03_01_2023', '04_01_2023', '05_01_2023',
       '06_01_2023', '07_01_2023', '08_01_2023', '09_01_2023', '10_01_2023',
       '11_01_2023', '12_01_2023', '13_01_2023', '14_01_2023', '15_01_2023',
       '16_01_2023', '17_01_2023', '18_01_2023', '19_01_2023', '20_01_2023',
       '21_01_2023', '22_01_2023', '23_01_2023', '24_01_2023', '25_01_2023',
       '26_01_2023', '27_01_2023', '28_01_2023', '29_01_2023', '30_01_2023',
       '31_01_2023', '01_02_2023', '02_02_2023', '03_02_2023', '04_02_2023',
       '05_02_2023', '06_02_2023', '07_02_2023', '08_02_2023', '09_02_2023',
       '10_02_2023'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
df=pd.DataFrame(lists,columns=['sno','name','value'])
print(df)

   sno name  value
0    1  aaa     22
1    2  bbb     25
2    3  ccc     24
